/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.payroll.system;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shauryanratan
 */
public class AttendancePage extends javax.swing.JFrame {

    /**
     * Creates new form AttendancePage
     */
    private int ID = -1;
    public AttendancePage(int ID) {
        initComponents();
        this.ID = ID;
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        updateTable();
    }
    public ArrayList<AttendanceModel> getEmployeesAttendance() {
        ArrayList<AttendanceModel> list = new ArrayList<AttendanceModel>();
        String sql = "select * from attendance where id = "+ID;
        Connection con = DB.connect();
        AttendanceModel user = null;
        try{
            list.clear();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                String date = rs.getString("date");
                int id = rs.getInt("id");
                String att = rs.getString("att");
                String type = rs.getString("type");
                String reason = rs.getString("reason");
                user = new AttendanceModel(date,id,att,type,reason);
                list.add(user);
            }
            con.close();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Attendance couldn't be fetched", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return list;
    }

    public void updateTable() {
        ArrayList<AttendanceModel> list = getEmployeesAttendance();
        DefaultTableModel model = (DefaultTableModel) tbl_Attendance.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getDate();
            row[1] = list.get(i).getId();
            row[2] = list.get(i).getAtt();
            row[3] = list.get(i).getType();
            row[4] = list.get(i).getReason();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_Attendance = new javax.swing.JTable();
        btn_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Attendance");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Employees Attendance");

        tbl_Attendance.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        tbl_Attendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Employee Code", "Absences", "Type of Absence", "Absence Reason"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_AttendanceMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_Attendance);

        btn_Back.setText("Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(180, 180, 180)
                .addComponent(btn_Back)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_AttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_AttendanceMouseClicked
        

    }//GEN-LAST:event_tbl_AttendanceMouseClicked

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // TODO add your handling code here:
        int exit = (JOptionPane.showConfirmDialog(null, "Are you sure you want to exit the form", "Exit", JOptionPane.YES_NO_CANCEL_OPTION));
        if (exit == 0) {
            MainPage_Emp page = new MainPage_Emp(ID);
            page.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbl_Attendance;
    // End of variables declaration//GEN-END:variables
}
