/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.payroll.system;

import javax.swing.JOptionPane;

/**
 *
 * @author shauryanratan
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    private String user = "";
    public MainPage() {
        initComponents();
        lbl_EmpCode.setText(user);
    }

    MainPage(String post) {
        initComponents();
        this.user = post;
        lbl_EmpCode.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        btn_LogOut = new javax.swing.JButton();
        btn_Attendance = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_EditEmpl = new javax.swing.JButton();
        btn_EmpProfile = new javax.swing.JButton();
        btn_EmpReport = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbl_EmpCode = new javax.swing.JLabel();
        btn_Exit = new javax.swing.JButton();
        btn_Profile1 = new javax.swing.JButton();
        btn_Salary1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("R.K. Transport and Services");

        btn_LogOut.setText("Log Out");
        btn_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogOutActionPerformed(evt);
            }
        });

        btn_Attendance.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_Attendance.setText("Attendance");
        btn_Attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AttendanceActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText("Welcome back ");

        btn_EditEmpl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_EditEmpl.setText("Edit Employees");
        btn_EditEmpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditEmplActionPerformed(evt);
            }
        });

        btn_EmpProfile.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_EmpProfile.setText("Employee Registration");
        btn_EmpProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpProfileActionPerformed(evt);
            }
        });

        btn_EmpReport.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_EmpReport.setText("Employee Reports");
        btn_EmpReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpReportActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Main Menu");

        lbl_EmpCode.setFont(new java.awt.Font("Lucida Grande", 3, 16)); // NOI18N

        btn_Exit.setText("Exit");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        btn_Profile1.setText("Create New Profile");
        btn_Profile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Profile1ActionPerformed(evt);
            }
        });

        btn_Salary1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_Salary1.setText("Salary");
        btn_Salary1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Salary1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Attendance, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(btn_Salary1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_EmpReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_EmpProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(btn_Profile1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl_EmpCode, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_LogOut)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btn_EditEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Exit)
                            .addComponent(btn_Profile1))
                        .addGap(10, 10, 10)
                        .addComponent(btn_LogOut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_EmpCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_EmpProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_EmpReport, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Salary1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btn_EditEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogOutActionPerformed
        LoginPage page = new LoginPage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_LogOutActionPerformed

    private void btn_AttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AttendanceActionPerformed
        AttendanceViewPage page = new AttendanceViewPage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_AttendanceActionPerformed

    private void btn_EditEmplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditEmplActionPerformed
        UpdateEmployeeForm page = new UpdateEmployeeForm();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_EditEmplActionPerformed

    private void btn_EmpProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpProfileActionPerformed
        NewEmployeeForm page = new NewEmployeeForm();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_EmpProfileActionPerformed

    private void btn_EmpReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpReportActionPerformed
        // TODO add your handling code here:
        EmployeeReportPage page = new EmployeeReportPage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_EmpReportActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        // TODO add your handling code here:
        int exit = (JOptionPane.showConfirmDialog(null, "Are you sure you want to exit the application", "Exit", JOptionPane.YES_NO_CANCEL_OPTION));
        if (exit == 0) {
            System.exit(0);
        }

    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_Profile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Profile1ActionPerformed
        ProfilePage page = new ProfilePage();
        if(page.hasEmployees){
            page.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_Profile1ActionPerformed

    private void btn_Salary1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Salary1ActionPerformed
        SalaryPage page = new SalaryPage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Salary1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Attendance;
    private javax.swing.JButton btn_EditEmpl;
    private javax.swing.JButton btn_EmpProfile;
    private javax.swing.JButton btn_EmpReport;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_LogOut;
    private javax.swing.JButton btn_Profile1;
    private javax.swing.JButton btn_Salary1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lbl_EmpCode;
    // End of variables declaration//GEN-END:variables
}
